# Use root/example as user/password credentials
version: '3.1'
services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: boarding_house
      MYSQL_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3304:3306'
    expose:
      # Opens port 3306 on the container
      - '3304'
    volumes:
      - D:\dev\data\mariadb\nhatro:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: