spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
server:
  port: ${SERVER_PORT:2105}

app:
  security:
    enabled: true
    jwt:
      secret-key: ${JWT_SECRET_KEY}
  file:
    type: ${FILE_TYPE:nhatro}
    apiKey: ${FILE_API_KEY}
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
api:
  file:
    url: ${FILE_SERVER_URL}