spring:
  application:
    name: boarding-house
  datasource:
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3304/boarding_house
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui/index.html
  flyway:
    schemas: boarding_house
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baselineOnMigrate: true
    baseline-version: 0
    enabled: true
    locations: classpath:db/migration
log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: 'trace '
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG
    root: INFO
security:
  ignore:
    paths: /swagger-ui,/v3/api-docs,/api/v1/auth,/v1/external,/ws
server:
  port: '8080'
app:
  security:
    enabled: false
  file:
    apiKey: 7ff7fd0e-514d-4cda-acbc-66dc30adae92
    type: dev
api:
  file:
    url: http://localhost:8081
